[2025-09-12T07:48:27.369+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_bronze_load manual__2025-09-12T07:48:09.966613+00:00 [queued]>
[2025-09-12T07:48:27.371+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aviationstack_kafka_dag.run_bronze_load manual__2025-09-12T07:48:09.966613+00:00 [queued]>
[2025-09-12T07:48:27.371+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-12T07:48:27.375+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bronze_load> on 2025-09-12 07:48:09.966613+00:00
[2025-09-12T07:48:27.377+0000] {standard_task_runner.py:60} INFO - Started process 1361 to run task
[2025-09-12T07:48:27.378+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'aviationstack_kafka_dag', 'run_bronze_load', 'manual__2025-09-12T07:48:09.966613+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/aviationstack_dag.py', '--cfg-path', '/tmp/tmpzztfk5ve']
[2025-09-12T07:48:27.379+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask run_bronze_load
[2025-09-12T07:48:27.398+0000] {task_command.py:423} INFO - Running <TaskInstance: aviationstack_kafka_dag.run_bronze_load manual__2025-09-12T07:48:09.966613+00:00 [running]> on host eba0e74bcf84
[2025-09-12T07:48:27.424+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='aviationstack_kafka_dag' AIRFLOW_CTX_TASK_ID='run_bronze_load' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T07:48:09.966613+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T07:48:09.966613+00:00'
[2025-09-12T07:48:27.435+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-12T07:48:27.437+0000] {logging_mixin.py:188} INFO - [INFO] Reading data from JSON file
[2025-09-12T07:48:27.437+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etl/bronze/avstack/bronze_load.py", line 33, in insert_into_bronze_ddl
    with open(filepath, "r") as f:
         ^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-09-12T07:48:27.441+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=aviationstack_kafka_dag, task_id=run_bronze_load, execution_date=20250912T074809, start_date=20250912T074827, end_date=20250912T074827
[2025-09-12T07:48:27.444+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task run_bronze_load (expected str, bytes or os.PathLike object, not NoneType; 1361)
[2025-09-12T07:48:27.475+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-12T07:48:27.485+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
